title: Shazaq
description: Abandon all hope ye who enter here
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shazaq.github.io"

# Build settings

plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css 


collections:
  projects:
    output: true
    permalink: /projects-&-writeups/:title/
  blog:
    output: true
    permalink: /blog/:title/



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
