export const ProjectData = [
	{
		index: 1,
		name: "Redux - Contact App",
		image: "/images/contact-app-project-thumb.PNG",
		glink: "https://github.com/shazaq03/react-redux-contacts-app.git",
		Llink: "https://shazaq03.github.io/react-redux-contacts-app/",
		description: "",
	},
	{
		index: 2,
		name: "Paimon's Handbook",
		image: "/images/paimons-handbook-project-thumb.png",
		glink: "https://github.com/shazaq03/paimons-handbook",
		Llink: "https://paimons-handbook.netlify.app/",
		description: "",
	},
	{
		index: 3,
		name: "React - Recipe App",
		image: "/images/recipe-app-project-thumb.PNG",
		glink: "https://github.com/shazaq03/react-recipe-app.git",
		Llink: "https://shazaq03.github.io/react-recipe-app/",
		description: "",
	},
	{
		index: 4,
		name: "React - Todo list",
		image: "/images/todo-app-project-thumb.PNG",
		glink: "https://github.com/shazaq03/react-todo-list",
		Llink: "https://shazaq03.github.io/react-todo-list/",
		description: "",
	},
	{
		index: 5,
		name: "Js - Classic snake game",
		image: "/images/snake-game-project-thumb.PNG",
		glink: "https://github.com/shazaq03/snake-game",
		Llink: "https://shazaq03.github.io/snake-game/",
		description: "",
	},
];
